// tests/NodeFileSystem.test.ts

import { describe, expect, it, afterEach } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { NodeFileSystem } from "../src/adapters/filesystem/NodeFileSystem";

describe("NodeFileSystem", () => {
  const fileSystem = new NodeFileSystem();

  const temporaryDirectories: string[] = [];

  afterEach(async () => {
    for (const directory of temporaryDirectories) {
      await rm(directory, {
        recursive: true,
        force: true,
      });
    }

    temporaryDirectories.length = 0;
  });

  async function createTemporaryDirectory(): Promise<string> {
    const directory = await mkdtemp(join(tmpdir(), "fileforge-test-"));

    temporaryDirectories.push(directory);

    return directory;
  }

  it("returns true when a file exists", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await writeFile(filePath, "hello", "utf8");

    await expect(fileSystem.exists(filePath)).resolves.toBe(true);
  });

  it("returns false when a path does not exist", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "missing.txt");

    await expect(fileSystem.exists(filePath)).resolves.toBe(false);
  });

  it("returns true when a path is a directory", async () => {
    const directory = await createTemporaryDirectory();

    await expect(fileSystem.isDirectory(directory)).resolves.toBe(true);
  });

  it("returns false when a path is a file", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await writeFile(filePath, "hello", "utf8");

    await expect(fileSystem.isDirectory(filePath)).resolves.toBe(false);
  });

  it("returns false when checking a missing directory", async () => {
    const directory = await createTemporaryDirectory();
    const missingDirectory = join(directory, "missing");

    await expect(fileSystem.isDirectory(missingDirectory)).resolves.toBe(false);
  });

  it("can access an existing file", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await writeFile(filePath, "hello", "utf8");

    await expect(fileSystem.canAccess(filePath)).resolves.toBe(true);
  });

  it("cannot access a missing path", async () => {
    const directory = await createTemporaryDirectory();
    const missingPath = join(directory, "missing.txt");

    await expect(fileSystem.canAccess(missingPath)).resolves.toBe(false);
  });

  it("reads file contents", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await writeFile(filePath, "FileForge test content", "utf8");

    await expect(fileSystem.readFile(filePath)).resolves.toBe(
      "FileForge test content",
    );
  });

  it("writes file contents", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await fileSystem.writeFile(filePath, "Generated by FileForge");

    const content = await readFile(filePath, "utf8");

    expect(content).toBe("Generated by FileForge");
  });

  it("overwrites existing file contents", async () => {
    const directory = await createTemporaryDirectory();
    const filePath = join(directory, "test.txt");

    await writeFile(filePath, "old content", "utf8");

    await fileSystem.writeFile(filePath, "new content");

    const content = await readFile(filePath, "utf8");

    expect(content).toBe("new content");
  });

  it("creates a directory", async () => {
    const directory = await createTemporaryDirectory();
    const newDirectory = join(directory, "src");

    await fileSystem.createDirectory(newDirectory);

    await expect(fileSystem.exists(newDirectory)).resolves.toBe(true);

    await expect(fileSystem.isDirectory(newDirectory)).resolves.toBe(true);
  });

  it("creates nested directories recursively", async () => {
    const directory = await createTemporaryDirectory();

    const nestedDirectory = join(directory, "src", "components", "buttons");

    await fileSystem.createDirectory(nestedDirectory);

    await expect(fileSystem.exists(nestedDirectory)).resolves.toBe(true);

    await expect(fileSystem.isDirectory(nestedDirectory)).resolves.toBe(true);
  });

  it("allows writing a file inside a newly created nested directory", async () => {
    const directory = await createTemporaryDirectory();

    const nestedDirectory = join(directory, "src", "components");

    await fileSystem.createDirectory(nestedDirectory);

    const filePath = join(nestedDirectory, "Button.tsx");

    await fileSystem.writeFile(filePath, "export default function Button() {}");

    const content = await fileSystem.readFile(filePath);

    expect(content).toBe("export default function Button() {}");
  });

  it("can access a directory", async () => {
    const directory = await createTemporaryDirectory();

    await expect(fileSystem.canAccess(directory)).resolves.toBe(true);
  });
});
